# Generated by Django 3.2.3 on 2021-06-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(help_text='Nombre del item.', max_length=150, verbose_name='Nombre')),
                ('pvp', models.DecimalField(decimal_places=3, help_text='Precio de venta con IVA', max_digits=9, verbose_name='Precio')),
                ('photo', models.ImageField(help_text='Foto principal del item.', upload_to='item/', verbose_name='Foto')),
                ('description', models.TextField(blank=True, default='', help_text='Descripción del item.', verbose_name='Descripción')),
                ('stock', models.BooleanField(default=True, verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
            },
        ),
    ]
