# Generated by Django 3.2.3 on 2021-06-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría', max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción de la categoría.', verbose_name='Descripción')),
                ('code', models.CharField(blank=True, help_text='Código referencial de la categoría', max_length=80, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['-name'],
            },
        ),
    ]
