# Generated by Django 3.2.3 on 2021-06-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0003_auto_20210608_2003'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código único de la transacción', max_length=60, unique=True, verbose_name='Código Transacción')),
                ('date_emi', models.DateTimeField(help_text='Fecha de emisión de la transacción', verbose_name='Fecha Emisión')),
                ('billing_address', models.CharField(help_text='Dirección de facturación', max_length=220, verbose_name='Dirección')),
                ('shipping_address', models.CharField(help_text='Dirección de entrega', max_length=220, verbose_name='Dirección Entrega')),
                ('tracking_status', models.IntegerField(choices=[(1, 'Procesada'), (2, 'Enviada'), (3, 'Pagada'), (4, 'Completada'), (5, 'Cancelada')], default=1, verbose_name='Estado de la orden')),
                ('payment_mode', models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Deposito o transferencia'), (3, 'Tarjeta de crédito')], default=1, verbose_name='Forma de pago')),
                ('subtotal_base_0', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal base 0', max_digits=9, verbose_name='Base 0')),
                ('subtotal_base_12', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal base 12', max_digits=9, verbose_name='Base 12')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal', max_digits=9, verbose_name='Sub Total')),
                ('tax_shipping', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Impuesto o fee para el envío.')),
                ('tax_12', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='IVA 12')),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total del orden.', max_digits=9, verbose_name='Total')),
                ('total_items', models.IntegerField(blank=True, default=0, help_text='Catntidad de items en la orden.', verbose_name='Total de items')),
                ('customer', models.ForeignKey(help_text='Cliente', on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='customers.customermodel')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio U.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.itemmodel', verbose_name='Item')),
                ('order', models.ForeignKey(help_text='Orden', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ordermodel')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'order_item',
            },
        ),
    ]
