# Generated by Django 3.2.3 on 2021-06-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BigIntegerField(default=0, verbose_name='Secuencia actual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha modificacion')),
            ],
            options={
                'verbose_name': 'Secuencia',
                'verbose_name_plural': 'Secuencias',
                'db_table': 'sequence',
            },
        ),
    ]
